### PR TITLE
Add KB2919442 as .NET 4.6 prerequisites

### LINKED ISSUE #24: Installation of .NET 4.6 on Windows 2012 R2 requires Windows updates
Installation of .NET 4.6 with this cookbook does not work on a Windows 2012 R2 eval box without windows updates.

The box has been created using "eval-win2012r2-standard" from https://github.com/boxcutter/windows, and has no windows update installed.

The `ms_dotnet_framework` fails. If I run manually the .NET installer, I see that some updates ([KB2919355](https://support.microsoft.com/en-us/kb/2919355)) are required:

virtualbox_amysta-cookbook_web_1466810330379_40128_25_06_2016_01_33_48

Do you think it is possible to install required Windows updates automatically with this Chef cookbook?

Or do I have to include the required Windows updates in my Windows box? Do you know if there are other requirements to install .NET on specific Windows versions? It would be great to list the requirements in this cookbook `README.md`.

### PR DESCRIPTION
**Pull request by Annih**
In order to fix #24, we need to install the prerequisites of the prerequisites :)

KB2919355 depends on KB2919442!

Cc: @aboten, @criteo-cookbooks/sre-core

### CODE REVIEW

**Comment by Annih** [comment]
@olivierlemasle  could you confirm that it works on your box?

**Comment by olivierlemasle** [comment]
Hi @Annih,

No, that does not work on my box. The problem is that a reboot is required between KB2919442 installation and KB2919355 installation. Currently, KB2919355 installation fails because of that.

And, seeing commit 7716fc98fcc, I guess you don't want to include the reboot action in the Chef recipe?

**Comment by Annih** [comment]
Yep I don't want to handle the reboot yet.
I would like to handle the reboot on the package provider, with an optional attribute `reboot_if_required` bound to some exit codes.
I have some ideas to hack this on a cookbook side, but I'ld prefere an official chef Core implementation :)

What is your use case? If it's in test-kitchen you should be able to use the new reboot and retry feature: https://discourse.chef.io/t/test-kitchen-1-10-0-released/8721

Is it ok for you?

**Comment by kamaradclimber** [comment]
+1

**Pull request merged**
