### PR TITLE
Fix idempotency of .NET 4.7.1 updates (KB405856)

### LINKED ISSUE #86: Needs better checking before deployment
In it's current form, the dotnet package is downloaded from MS along with updates. The package is extracted and installed along with updates (Three or four installer processes total) . During subsequent chef runs, the same events occur (extract the package, execute three or four processes) until windows realizes the packages are already installed, then it aborts.

This behaviour is ok for an underutilized server, but when running on a small instance that's under decent load, this process brings the host to an almost unresponsive state and will never complete before the next chef run. This really needs a better process to check and see if dotnot is already installed without having to extract and execute the multiple installers.

### PR DESCRIPTION
**Pull request by Annih**
The guard of the KB405856 package on Windows Server 2008R2 was wrong.
As explained in https://support.microsoft.com/help/4054856, it is setup as an Update on Windows Server 2012 and newer, but appears as a product on Windows Server 2008R2.

To fix this, changing the package name to match WS2008R2 product name would have work, but I think it's cleaner to define one package per KB and refers to the right one according to the Windows version.
Because the installer is the same, this introduce some code duplication but I think we can live with it :)

Fix #86

### CODE REVIEW

**Comment by Annih** [comment]
@nemesis519 could you test this patch in your environment? (I don't have 2008R2 box at the moment)

**Comment by jakauppila** [comment]
@Annih FYI the Bento project just added some Windows templates to their lineup, so there will be some up-to-date boxes!

https://app.vagrantup.com/tas50/boxes/windows_2008r2

**Comment by nemesis519** [comment]
@Annih I'll test this in a few hours and report back.

**Comment by Annih** [comment]
Ok @nemesis519 I managed to reproduced with tas50 box (;) @jakauppila )
Following Microsoft documentation, I did a small typo in the package name.

I updated my commit, it should be OK now, could you please confirm before I merge and release the new version?

Thanks a lot for your help.

**Comment by nemesis519** [comment]
@Annih Just tested and confirmed that it's working perfect now. Thanks for addressing this so quickly!

**Pull request merged**
