### PR TITLE
Add support for .Net 4.6.2. Replace KB2919442 with KB3021910.

### PR DESCRIPTION
**Pull request by Matasx**
- Added support for .Net 4.6.2
- Fixed issue #29 

Signed-off-by: Martin Matatko matatko.martin@gmail.com

### CODE REVIEW

**Comment by Annih** [comment]
Thanks @Matasx  I'll check this patch ASAP.

**Comment by Matasx** [comment]
Hi, could you please review? Thanks.

**Comment by Annih** [comment]
Just for my information @Matasx was it hard/complexe to perform this update on the `ms_dotnet` cookbook?

**Comment by Matasx** [comment]
Thanks for your notes. I will update my branch accordingly tomorrow. FYI it wasn't hard to perform those changes in cookbook itself. Only thing that was challenging for me was to find correct packages, prerequisites and registry checks on MS pages.

**Comment by Matasx** [comment]
@Annih, hopefully everything should by addressed now.

**Comment by Annih** [comment]
@Matasx I'll prepare a new `4.0` version of this cookbook including your fix and the pending PR, is it OK for you; or do you need a quicker release?

**Comment by Matasx** [comment]
@Annih thanks! What is your estimate? If it will be done somewhere in the middle of next week I think I am ok with that.

**Comment by Annih** [comment]
Release will be done today, but it'll be a 3.1 version instead of 4.0 as I previously said :)

**Pull request merged**
