### PR TITLE
update .NET 4.7.2 URLs

### PR DESCRIPTION
**Pull request by aae42**
see: issue #91

### CODE REVIEW

**Comment by aae42** [comment]
welll... now it's looking like this new package might have some prerequisites that the old one didn't...

needing to install KB2919355 to get 4.7.2 to install...

and i'm needing to install KB2975061 to get KB2919355 to install

**Comment by ekelundh** [comment]
Any update on the status of this PR?

**Comment by nemesis519** [comment]
Is it possible to get this pushed through?

**Comment by aae42** [comment]
@Annih i've removed the commits for the CHANGELOG and cookbook version bumps

**Pull request merged**
